apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume 
  labels:
    failure-domain-beta.kubernetes.io/zone: us-central1-a--us-central1-b
spec:
  capacity:
    storage: 400Gi
  accessMode:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4      